
.PHONY: freeze image tag

freeze:
	( echo "# this file is generated by 'make freeze'"; pip freeze | grep -v '.git@' ) > requirements.freeze.txt

image:
	docker build -t zarnovican/django-helloworld .

tag:
	docker tag zarnovican/django-helloworld zarnovican/django-helloworld:$(shell python setup.py --version | tr + _)

confd.bin:
	wget -O confd.bin https://github.com/zarnovican/confd/releases/download/v0.12.0-alpha3-51-g7ac1091/confd
	chmod 755 confd.bin

uwsgi.ini: confd.bin confd/templates/uwsgi.ini.tmpl
	./confd.bin -backend env -onetime -confdir ./confd/
